<?php
declare(strict_types=1);

final class AuthController
{
    public function __construct(private PDO $db, private array $config, private UserRepository $users) {}
    public function csrf(): never { Http::json(['success'=>true,'data'=>['csrf'=>$_SESSION['csrf']]]); }
    public function googleStatus(): never { Http::json(['success'=>true,'data'=>['configured'=>(bool)($this->config['google']['client_id']&&$this->config['google']['client_secret']&&$this->config['google']['redirect_uri'])]]); }
    public function me(): never { $user=$this->requireUser(); Http::json(['success'=>true,'data'=>['user'=>$this->users->public($user),'csrf'=>$_SESSION['csrf']]]); }
    public function register(): never
    { Session::requireCsrf();$d=Http::body();$name=$this->text($d,'name',2,120);$username=$this->text($d,'username',3,40);$email=strtolower($this->text($d,'email',6,190));$password=(string)($d['password']??'');$clan=trim((string)($d['clan']??'Ronin'))?:'Ronin';
      if(!preg_match('/^[A-Za-z0-9_]{3,40}$/',$username)||!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($password)<10) Http::json(['success'=>false,'message'=>'Provide a valid name, username, email, and password of at least 10 characters.'],422);
      if($this->users->byEmail($email)||$this->users->byLogin($username))Http::json(['success'=>false,'message'=>'An account with that email or username already exists.'],409);
      $id=$this->users->create($name,$username,$email,mb_substr($clan,0,80),password_hash($password,PASSWORD_DEFAULT));$token=bin2hex(random_bytes(32));$s=$this->db->prepare('INSERT INTO email_verifications (user_id,token_hash,expires_at) VALUES (?,?,DATE_ADD(NOW(),INTERVAL 24 HOUR))');$s->execute([$id,hash('sha256',$token)]);Mailer::verification($this->config,$email,$this->config['url'].'/api.php?route=auth/verify&token='.$token);Http::json(['success'=>true,'message'=>'Check your email to verify your account before signing in.'],201); }
    public function login(): never
    { Session::requireCsrf();$d=Http::body();$login=$this->text($d,'login',3,190);$password=(string)($d['password']??'');$user=$this->users->byLogin($login);if(!$user||!$user['password_hash']||!password_verify($password,$user['password_hash']))Http::json(['success'=>false,'message'=>'Invalid credentials.'],401);if(!$user['email_verified_at'])Http::json(['success'=>false,'message'=>'Verify your email before signing in.'],403);Session::login((int)$user['id']);Http::json(['success'=>true,'data'=>['user'=>$this->users->public($user),'csrf'=>$_SESSION['csrf']]]); }
    public function logout(): never { Session::requireCsrf();Session::logout();Http::json(['success'=>true,'message'=>'Signed out.']); }
    public function verify(): never
    { $token=(string)($_GET['token']??'');if(!preg_match('/^[a-f0-9]{64}$/',$token))Http::json(['success'=>false,'message'=>'Invalid verification link.'],400);$s=$this->db->prepare('SELECT user_id FROM email_verifications WHERE token_hash=? AND expires_at>NOW() AND used_at IS NULL');$s->execute([hash('sha256',$token)]);$row=$s->fetch();if(!$row)Http::json(['success'=>false,'message'=>'Verification link expired or already used.'],400);$this->users->markVerified((int)$row['user_id']);$s=$this->db->prepare('UPDATE email_verifications SET used_at=NOW() WHERE token_hash=?');$s->execute([hash('sha256',$token)]);Http::json(['success'=>true,'message'=>'Email verified. You can now sign in.']); }
    public function googleStart(): never
    { if(!$this->config['google']['client_id']||!$this->config['google']['redirect_uri'])Http::json(['success'=>false,'message'=>'Google OAuth is not configured.'],503);$state=bin2hex(random_bytes(32));$verifier=rtrim(strtr(base64_encode(random_bytes(32)),'+/','-_'),'=');$_SESSION['google_state']=$state;$_SESSION['google_verifier']=$verifier;$challenge=rtrim(strtr(base64_encode(hash('sha256',$verifier,true)),'+/','-_'),'=');$q=http_build_query(['client_id'=>$this->config['google']['client_id'],'redirect_uri'=>$this->config['google']['redirect_uri'],'response_type'=>'code','scope'=>'openid email profile','state'=>$state,'code_challenge'=>$challenge,'code_challenge_method'=>'S256','access_type'=>'online','prompt'=>'select_account']);header('Location: https://accounts.google.com/o/oauth2/v2/auth?'.$q, true,302);exit; }
    public function googleCallback(): never
    { $code=(string)($_GET['code']??'');$state=(string)($_GET['state']??'');if(!$code||!hash_equals($_SESSION['google_state']??'',$state))Http::json(['success'=>false,'message'=>'Google sign-in could not be verified.'],400);$post=http_build_query(['code'=>$code,'client_id'=>$this->config['google']['client_id'],'client_secret'=>$this->config['google']['client_secret'],'redirect_uri'=>$this->config['google']['redirect_uri'],'grant_type'=>'authorization_code','code_verifier'=>$_SESSION['google_verifier']??'']);$curl=curl_init('https://oauth2.googleapis.com/token');curl_setopt_array($curl,[CURLOPT_POST=>true,CURLOPT_POSTFIELDS=>$post,CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Content-Type: application/x-www-form-urlencoded']]);$result=curl_exec($curl);curl_close($curl);$token=json_decode((string)$result,true);if(!is_array($token)||empty($token['access_token']))Http::json(['success'=>false,'message'=>'Google token exchange failed.'],401);$curl=curl_init('https://openidconnect.googleapis.com/v1/userinfo');curl_setopt_array($curl,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_HTTPHEADER=>['Authorization: Bearer '.$token['access_token']]]);$profile=json_decode((string)curl_exec($curl),true);curl_close($curl);if(!is_array($profile)||empty($profile['sub'])||empty($profile['email'])||empty($profile['email_verified']))Http::json(['success'=>false,'message'=>'Google did not provide a verified email.'],401);$user=$this->users->byEmail(strtolower($profile['email']));if(!$user){$base=preg_replace('/[^A-Za-z0-9_]/','',strtolower(explode('@',$profile['email'])[0]))?:'shinobi';$username=$base;for($i=1;$this->users->byLogin($username);$i++)$username=substr($base,0,35).$i;$id=$this->users->create($profile['name']??$username,$username,strtolower($profile['email']),'Ronin',null,$profile['sub'],$profile['picture']??null,true);$user=$this->users->byId($id);}Session::login((int)$user['id']);header('Location: '.$this->config['url'].'/index.html?oauth=success',true,302);exit; }
    private function requireUser(): array { $id=Session::userId();$u=$id?$this->users->byId($id):null;if(!$u)Http::json(['success'=>false,'message'=>'Authentication required.'],401);return $u; }
    private function text(array $d,string $key,int $min,int $max): string { $v=trim((string)($d[$key]??''));if(mb_strlen($v)<$min||mb_strlen($v)>$max)Http::json(['success'=>false,'message'=>"$key is invalid."],422);return $v; }
}
